const reviewSchema = new Schema({
  review_id: Number,
  product_id: Number,
  rating: Number,
  date: { type: Date, default: Date.now },
  summary: String,
  body: String,
  reported: Boolean,
  recommend: Boolean,
  reviewer_name: String,
  reviewer_email: String,
  response: String,
  helpfulness: Number,
  photos: [String],
});
